### ISSUE TITLE
corrupted double-linked

### ISSUE THREAD

**Issue by kaen25** [DimaSmirnov/Archlinux-downgrader#11]
downgrader php-gd
 Downgrade package: php-gd
*** Error in `downgrader': corrupted double-linked list: 0x0000000000af32c0 ***
======= Backtrace: =========
/usr/lib/libc.so.6(+0x72055)[0x7f672525c055]
/usr/lib/libc.so.6(+0x779a6)[0x7f67252619a6]
/usr/lib/libc.so.6(+0x77c71)[0x7f6725261c71]
/usr/lib/libc.so.6(+0x78810)[0x7f6725262810]
downgrader[0x4025d8]
downgrader[0x401953]
downgrader[0x4029c9]
/usr/lib/libc.so.6(__libc_start_main+0xf0)[0x7f672520a610]
downgrader[0x401349]
======= Memory map: ========
00400000-00407000 r-xp 00000000 08:03 3041778                            /usr/bin/downgrader
00606000-00607000 rw-p 00006000 08:03 3041778                            /usr/bin/downgrader
00add000-00c6a000 rw-p 00000000 00:00 0                                  [heap]
7f671c000000-7f671c021000 rw-p 00000000 00:00 0
7f671c021000-7f6720000000 ---p 00000000 00:00 0
7f6720f24000-7f6720f29000 r-xp 00000000 08:03 3017938                    /usr/lib/libnss_dns-2.22.so
7f6720f29000-7f6721128000 ---p 00005000 08:03 3017938                    /usr/lib/libnss_dns-2.22.so
7f6721128000-7f6721129000 r--p 00004000 08:03 3017938                    /usr/lib/libnss_dns-2.22.so
7f6721129000-7f672112a000 rw-p 00005000 08:03 3017938                    /usr/lib/libnss_dns-2.22.so
7f672112a000-7f6721135000 r-xp 00000000 08:03 3017939                    /usr/lib/libnss_files-2.22.so
7f6721135000-7f6721334000 ---p 0000b000 08:03 3017939                    /usr/lib/libnss_files-2.22.so
7f6721334000-7f6721335000 r--p 0000a000 08:03 3017939                    /usr/lib/libnss_files-2.22.so
7f6721335000-7f6721336000 rw-p 0000b000 08:03 3017939                    /usr/lib/libnss_files-2.22.so
7f6721336000-7f672133c000 rw-p 00000000 00:00 0
7f672133c000-7f672133d000 ---p 00000000 00:00 0
7f672133d000-7f6721b3d000 rw-p 00000000 00:00 0
7f6721b3d000-7f6721b51000 r-xp 00000000 08:03 3017946                    /usr/lib/libresolv-2.22.so
7f6721b51000-7f6721d50000 ---p 00014000 08:03 3017946                    /usr/lib/libresolv-2.22.so
7f6721d50000-7f6721d51000 r--p 00013000 08:03 3017946                    /usr/lib/libresolv-2.22.so
7f6721d51000-7f6721d52000 rw-p 00014000 08:03 3017946                    /usr/lib/libresolv-2.22.so
7f6721d52000-7f6721d54000 rw-p 00000000 00:00 0
7f6721d54000-7f6721d57000 r-xp 00000000 08:03 3024581                    /usr/lib/libkeyutils.so.1.5
7f6721d57000-7f6721f56000 ---p 00003000 08:03 3024581                    /usr/lib/libkeyutils.so.1.5
7f6721f56000-7f6721f57000 r--p 00002000 08:03 3024581                    /usr/lib/libkeyutils.so.1.5
7f6721f57000-7f6721f58000 rw-p 00003000 08:03 3024581                    /usr/lib/libkeyutils.so.1.5
7f6721f58000-7f6721f64000 r-xp 00000000 08:03 3024615                    /usr/lib/libkrb5support.so.0.1
7f6721f64000-7f6722163000 ---p 0000c000 08:03 3024615                    /usr/lib/libkrb5support.so.0.1
7f6722163000-7f6722164000 r--p 0000b000 08:03 3024615                    /usr/lib/libkrb5support.so.0.1
7f6722164000-7f6722165000 rw-p 0000c000 08:03 3024615                    /usr/lib/libkrb5support.so.0.1
7f6722165000-7f6722168000 r-xp 00000000 08:03 3017943                    /usr/lib/libdl-2.22.so
7f6722168000-7f6722367000 ---p 00003000 08:03 3017943                    /usr/lib/libdl-2.22.so
7f6722367000-7f6722368000 r--p 00002000 08:03 3017943                    /usr/lib/libdl-2.22.so
7f6722368000-7f6722369000 rw-p 00003000 08:03 3017943                    /usr/lib/libdl-2.22.so
7f6722369000-7f6722378000 r-xp 00000000 08:03 3020890                    /usr/lib/libbz2.so.1.0.6
7f6722378000-7f6722577000 ---p 0000f000 08:03 3020890                    /usr/lib/libbz2.so.1.0.6
7f6722577000-7f6722579000 rw-p 0000e000 08:03 3020890                    /usr/lib/libbz2.so.1.0.6
7f6722579000-7f672259e000 r-xp 00000000 08:03 3025813                    /usr/lib/liblzma.so.5.2.2
7f672259e000-7f672279d000 ---p 00025000 08:03 3025813                    /usr/lib/liblzma.so.5.2.2
7f672279d000-7f672279e000 r--p 00024000 08:03 3025813                    /usr/lib/liblzma.so.5.2.2
7f672279e000-7f672279f000 rw-p 00025000 08:03 3025813                    /usr/lib/liblzma.so.5.2.2
7f672279f000-7f67227c0000 r-xp 00000000 08:03 3027495                    /usr/lib/liblzo2.so.2.0.0
7f67227c0000-7f67229bf000 ---p 00021000 08:03 3027495                    /usr/lib/liblzo2.so.2.0.0
7f67229bf000-7f67229c0000 r--p 00020000 08:03 3027495                    /usr/lib/liblzo2.so.2.0.0
7f67229c0000-7f67229c1000 rw-p 00021000 08:03 3027495                    /usr/lib/liblzo2.so.2.0.0
7f67229c1000-7f67229e8000 r-xp 00000000 08:03 3025421                    /usr/lib/libexpat.so.1.6.0
7f67229e8000-7f6722be7000 ---p 00027000 08:03 3025421                    /usr/lib/libexpat.so.1.6.0
7f6722be7000-7f6722bea000 r--p 00026000 08:03 3025421                    /usr/lib/libexpat.so.1.6.0
7f6722bea000-7f6722beb000 rw-p 00029000 08:03 3025421                    /usr/lib/libexpat.so.1.6.0
7f6722beb000-7f6722bef000 r-xp 00000000 08:03 3025028                    /usr/lib/libattr.so.1.1.0
7f6722bef000-7f6722dee000 ---p 00004000 08:03 3025028                    /usr/lib/libattr.so.1.1.0
7f6722dee000-7f6722def000 r--p 00003000 08:03 3025028                    /usr/lib/libattr.so.1.1.0
7f6722def000-7f6722df0000 rw-p 00004000 08:03 3025028                    /usr/lib/libattr.so.1.1.0
7f6722df0000-7f6722df8000 r-xp 00000000 08:03 3025063                    /usr/lib/libacl.so.1.1.0
7f6722df8000-7f6722ff7000 ---p 00008000 08:03 3025063                    /usr/lib/libacl.so.1.1.0
7f6722ff7000-7f6722ff8000 r--p 00007000 08:03 3025063                    /usr/lib/libacl.so.1.1.0
7f6722ff8000-7f6722ff9000 rw-p 00008000 08:03 3025063                    /usr/lib/libacl.so.1.1.0
7f6722ff9000-7f672300c000 r-xp 00000000 08:03 3048717                    /usr/lib/libgpg-error.so.0.17.0
7f672300c000-7f672320b000 ---p 00013000 08:03 3048717                    /usr/lib/libgpg-error.so.0.17.0
7f672320b000-7f672320c000 r--p 00012000 08:03 3048717                    /usr/lib/libgpg-error.so.0.17.0
7f672320c000-7f672320d000 rw-p 00013000 08:03 3048717                    /usr/lib/libgpg-error.so.0.17.0
7f672320d000-7f672321f000 r-xp 00000000 08:03 3042936                    /usr/lib/libassuan.so.0.7.2
7f672321f000-7f672341e000 ---p 00012000 08:03 3042936                    /usr/lib/libassuan.so.0.7.2
7f672341e000-7f672341f000 r--p 00011000 08:03 3042936                    /usr/lib/libassuan.so.0.7.2
7f672341f000-7f6723420000 rw-p 00012000 08:03 3042936                    /usr/lib/libassuan.so.0.7.2
7f6723420000-7f6723438000 r-xp 00000000 08:03 3017841                    /usr/lib/libpthread-2.22.so
7f6723438000-7f6723637000 ---p 00018000 08:03 3017841                    /usr/lib/libpthread-2.22.so
7f6723637000-7f6723638000 r--p 00017000 08:03 3017841                    /usr/lib/libpthread-2.22.so
7f6723638000-7f6723639000 rw-p 00018000 08:03 3017841                    /usr/lib/libpthread-2.22.so
7f6723639000-7f672363d000 rw-p 00000000 00:00 0
7f672363d000-7f6723652000 r-xp 00000000 08:03 3020894                    /usr/lib/libz.so.1.2.8
7f6723652000-7f6723851000 ---p 00015000 08:03 3020894                    /usr/lib/libz.so.1.2.8
7f6723851000-7f6723852000 r--p 00014000 08:03 3020894                    /usr/lib/libz.so.1.2.8
7f6723852000-7f6723853000 rw-p 00015000 08:03 3020894                    /usr/lib/libz.so.1.2.8
7f6723853000-7f6723856000 r-xp 00000000 08:03 3021085                    /usr/lib/libcom_err.so.2.1
7f6723856000-7f6723a55000 ---p 00003000 08:03 3021085                    /usr/lib/libcom_err.so.2.1
7f6723a55000-7f6723a56000 r--p 00002000 08:03 3021085                    /usr/lib/libcom_err.so.2.1
7f6723a56000-7f6723a57000 rw-p 00003000 08:03 3021085                    /usr/lib/libcom_err.so.2.1
7f6723a57000-7f6723a85000 r-xp 00000000 08:03 3024617                    /usr/lib/libk5crypto.so.3.1
7f6723a85000-7f6723c84000 ---p 0002e000 08:03 3024617                    /usr/lib/libk5crypto.so.3.1
7f6723c84000-7f6723c86000 r--p 0002d000 08:03 3024617                    /usr/lib/libk5crypto.so.3.1
7f6723c86000-7f6723c87000 rw-p 0002f000 08:03 3024617                    /usr/lib/libk5crypto.so.3.1
7f6723c87000-7f6723c88000 rw-p 00000000 00:00 0
7f6723c88000-7f6723d5d000 r-xp 00000000 08:03 3024618                    /usr/lib/libkrb5.so.3.3
7f6723d5d000-7f6723f5d000 ---p 000d5000 08:03 3024618                    /usr/lib/libkrb5.so.3.3
7f6723f5d000-7f6723f6a000 r--p 000d5000 08:03 3024618                    /usr/lib/libkrb5.so.3.3
7f6723f6a000-7f6723f6d000 rw-p 000e2000 08:03 3024618                    /usr/lib/libkrb5.so.3.3
7f6723f6d000-7f6723fb7000 r-xp 00000000 08:03 3024619                    /usr/lib/libgssapi_krb5.so.2.2
7f6723fb7000-7f67241b6000 ---p 0004a000 08:03 3024619                    /usr/lib/libgssapi_krb5.so.2.2
7f67241b6000-7f67241b8000 r--p 00049000 08:03 3024619                    /usr/lib/libgssapi_krb5.so.2.2
7f67241b8000-7f67241ba000 rw-p 0004b000 08:03 3024619                    /usr/lib/libgssapi_krb5.so.2.2
7f67241ba000-7f672422a000 r-xp 00000000 08:03 3048728                    /usr/lib/libssl.so.1.0.0
7f672422a000-7f6724429000 ---p 00070000 08:03 3048728                    /usr/lib/libssl.so.1.0.0
7f6724429000-7f672442e000 r--p 0006f000 08:03 3048728                    /usr/lib/libssl.so.1.0.0
7f672442e000-7f6724435000 rw-p 00074000 08:03 3048728                    /usr/lib/libssl.so.1.0.0
7f6724435000-7f672445f000 r-xp 00000000 08:03 3031590                    /usr/lib/libssh2.so.1.0.1
7f672445f000-7f672465f000 ---p 0002a000 08:03 3031590                    /usr/lib/libssh2.so.1.0.1
7f672465f000-7f6724660000 r--p 0002a000 08:03 3031590                    /usr/lib/libssh2.so.1.0.1
7f6724660000-7f6724661000 rw-p 0002b000 08:03 3031590                    /usr/lib/libssh2.so.1.0.1
7f6724661000-7f6724693000 r-xp 00000000 08:03 3044993                    /usr/lib/libidn.so.11.6.15
7f6724693000-7f6724893000 ---p 00032000 08:03 3044993                    /usr/lib/libidn.so.11.6.15
7f6724893000-7f6724894000 r--p 00032000 08:03 3044993                    /usr/lib/libidn.so.11.6.15
7f6724894000-7f6724895000 rw-p 00033000 08:03 3044993                    /usr/lib/libidn.so.11.6.15
7f6724895000-7f6724ae3000 r-xp 00000000 08:03 3048729                    /usr/lib/libcrypto.so.1.0.0
7f6724ae3000-7f6724ce2000 ---p 0024e000 08:03 3048729                    /usr/lib/libcrypto.so.1.0.0
7f6724ce2000-7f6724cfe000 r--p 0024d000 08:03 3048729                    /usr/lib/libcrypto.so.1.0.0
7f6724cfe000-7f6724d0a000 rw-p 00269000 08:03 3048729                    /usr/lib/libcrypto.so.1.0.0
7f6724d0a000-7f6724d0d000 rw-p 00000000 00:00 0
7f6724d0d000-7f6724dab000 r-xp 00000000 08:03 3027516                    /usr/lib/libarchive.so.13.1.2
7f6724dab000-7f6724fab000 ---p 0009e000 08:03 3027516                    /usr/lib/libarchive.so.13.1.2
7f6724fab000-7f6724fad000 r--p 0009e000 08:03 3027516                    /usr/lib/libarchive.so.13.1.2
7f6724fad000-7f6724faf000 rw-p 000a0000 08:03 3027516                    /usr/lib/libarchive.so.13.1.2
7f6724faf000-7f6724fb0000 rw-p 00000000 00:00 0
7f6724fb0000-7f6724fe8000 r-xp 00000000 08:03 3032005                    /usr/lib/libgpgme.so.11.14.0
7f6724fe8000-7f67251e7000 ---p 00038000 08:03 3032005                    /usr/lib/libgpgme.so.11.14.0
7f67251e7000-7f67251e8000 r--p 00037000 08:03 3032005                    /usr/lib/libgpgme.so.11.14.0
7f67251e8000-7f67251ea000 rw-p 00038000 08:03 3032005                    /usr/lib/libgpgme.so.11.14.0
7f67251ea000-7f6725385000 r-xp 00000000 08:03 3017880                    /usr/lib/libc-2.22.so
7f6725385000-7f6725584000 ---p 0019b000 08:03 3017880                    /usr/lib/libc-2.22.so
7f6725584000-7f6725588000 r--p 0019a000 08:03 3017880                    /usr/lib/libc-2.22.so
7f6725588000-7f672558a000 rw-p 0019e000 08:03 3017880                    /usr/lib/libc-2.22.so
7f672558a000-7f672558e000 rw-p 00000000 00:00 0
7f672558e000-7f67255a4000 r-xp 00000000 08:03 3021132                    /usr/lib/libgcc_s.so.1
7f67255a4000-7f67257a3000 ---p 00016000 08:03 3021132                    /usr/lib/libgcc_s.so.1
7f67257a3000-7f67257a4000 rw-p 00015000 08:03 3021132                    /usr/lib/libgcc_s.so.1
7f67257a4000-7f67258a1000 r-xp 00000000 08:03 3017944                    /usr/lib/libm-2.22.so
7f67258a1000-7f6725aa0000 ---p 000fd000 08:03 3017944                    /usr/lib/libm-2.22.so
7f6725aa0000-7f6725aa1000 r--p 000fc000 08:03 3017944                    /usr/lib/libm-2.22.so
7f6725aa1000-7f6725aa2000 rw-p 000fd000 08:03 3017944                    /usr/lib/libm-2.22.so
7f6725aa2000-7f6725c14000 r-xp 00000000 08:03 3042429                    /usr/lib/libstdc++.so.6.0.21
7f6725c14000-7f6725e14000 ---p 00172000 08:03 3042429                    /usr/lib/libstdc++.so.6.0.21
7f6725e14000-7f6725e1e000 r--p 00172000 08:03 3042429                    /usr/lib/libstdc++.so.6.0.21
7f6725e1e000-7f6725e20000 rw-p 0017c000 08:03 3042429                    /usr/lib/libstdc++.so.6.0.21
7f6725e20000-7f6725e24000 rw-p 00000000 00:00 0
7f6725e24000-7f6725e94000 r-xp 00000000 08:03 3041717                    /usr/lib/libcurl.so.4.4.0
7f6725e94000-7f6726094000 ---p 00070000 08:03 3041717                    /usr/lib/libcurl.so.4.4.0
7f6726094000-7f6726096000 r--p 00070000 08:03 3041717                    /usr/lib/libcurl.so.4.4.0
7f6726096000-7f6726097000 rw-p 00072000 08:03 3041717                    /usr/lib/libcurl.so.4.4.0
7f6726097000-7f6726098000 rw-p 00000000 00:00 0
7f6726098000-7f67260c9000 r-xp 00000000 08:03 3032044                    /usr/lib/libalpm.so.9.0.1
7f67260c9000-7f67262c8000 ---p 00031000 08:03 3032044                    /usr/lib/libalpm.so.9.0.1
7f67262c8000-7f67262c9000 rw-p 00030000 08:03 3032044                    /usr/lib/libalpm.so.9.0.1
7f67262c9000-7f67262eb000 r-xp 00000000 08:03 3017878                    /usr/lib/ld-2.22.so
7f6726472000-7f67264ea000 rw-p 00000000 00:00 0
7f67264ea000-7f67264eb000 r--p 00021000 08:03 3017878                    /usr/lib/ld-2.22.so
7f67264eb000-7f67264ec000 rw-p 00022000 08:03 3017878                    /usr/lib/ld-2.22.so
7f67264ec000-7f67264ed000 rw-p 00000000 00:00 0
7ffc55e1e000-7ffc55e3f000 rw-p 00000000 00:00 0                          [stack]
7ffc55efd000-7ffc55eff000 r--p 00000000 00:00 0                          [vvar]
7ffc55eff000-7ffc55f01000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
Abandon (core dumped)

**Comment by DimaSmirnov** [comment]
Please update downgrader from AUR.
Looks like I fix this bug 2 days ago.
Thanks!
